from odoo import models, fields, _
from odoo.exceptions import UserError, ValidationError


# class lavish_confirm_wizard(models.TransientModel):
#     _name = 'lavish.confirm.wizard'
#     _description = 'Confirmaci√≥n de procesos lavish'

#     yes_no = fields.Char(default='Desea continuar?')

#     def yes(self):
#         return True


